Improve performance querying group_folders_manage
nextcloud/groupfolders pull request #1016
Opened 2020-08-21 03:28 UTC by jeffpardy

We noticed a linear decrease in querying group folders are more folders were created.

This replaces the individual queries per folder with a single call to get all rows from `group_folders_manage`.

2020-08-24 13:55 UTC, icewind1991 requested changes
seems good otherwise

2020-08-24 13:55 UTC, icewind1991 commented on lib/Folder/FolderManager.php
> +			$mappings = $folderMappings[$id];
```suggestion
			$mappings = $folderMappings[$id] ?? [];
```

to handle the case where there is no mapping for the folder

2020-08-24 15:27 UTC, jeffpardy commented
Thanks @icewind1991, updated.

2020-08-25 14:32 UTC, icewind1991 approved these changes

2020-09-01 08:25 UTC, juliushaertl approved these changes

2020-09-01 08:26 UTC, merged

2020-09-07 08:29 UTC, landryb commented
Nice! Thanks