fix Oracle query limit compliance
nextcloud/groupfolders pull request #1804
Opened 2021-12-07 09:56 UTC by to-kn

these changes fixed the Problems with #1702 for me

2021-12-07 11:14 UTC, fschrempf requested changes
Thanks for the contribution! I think it would be better to add the chunking directly in `getFoldersForGroups()` instead of implementing it in multiple places. And a comment with the reason for the chunking would be nice.

2021-12-07 11:54 UTC, fschrempf commented
You can have a look at https://github.com/nextcloud/server/pull/27187 or https://github.com/nextcloud/mail/pull/4947 for other places where this was fixed. I also opened an issue (#1805) to check any other queries that might hit the limitations.

2021-12-17 11:38 UTC, to-kn commented
HI @fschrempf do you mean like that? To be honest i did not had the possibility to validate the fix like that...

2021-12-19 21:24 UTC, fschrempf requested changes
The code looks good to me. If you could add the comment I was asking for and squash the two commits into a single one, I think we are good to go.

2021-12-19 21:26 UTC, fschrempf commented
And we nee to find out why the unit tests fail. Might not be related to this PR, I haven't checked. Maybe rebasing already does the trick.

2021-12-20 07:28 UTC, to-kn commented
@fschrempf should be good

2021-12-20 08:27 UTC, CarlSchwan approved these changes
Code looks fine, let's wait for the tests results

2021-12-20 08:27 UTC, CarlSchwan commented on lib/Folder/FolderManager.php
> +        $folders = $this->getFoldersForGroups($groups, $rootStorageId);
```suggestion
       $folders = $this->getFoldersForGroups($groups, $rootStorageId);
```

2021-12-20 08:27 UTC, CarlSchwan commented on lib/Folder/FolderManager.php
> +        $folders = $this->getFoldersForGroups($groups);
```suggestion
       $folders = $this->getFoldersForGroups($groups);
```

2021-12-20 08:53 UTC, CarlSchwan requested changes
Tests are still failing and it seems to be directly related to this PR

2021-12-20 08:58 UTC, CarlSchwan commented on lib/Folder/FolderManager.php
> +            $query->setParameter('groupIds', $chunk, IQueryBuilder::PARAM_INT_ARRAY);
```suggestion
            $query->setParameter('groupIds', $chunk, IQueryBuilder::PARAM_STR_ARRAY);
```

Probably should fix the tests

2021-12-20 09:06 UTC, to-kn commented
@CarlSchwan thank you for your feed-back. I did not manage to get the Tests running locally so i was not able to check it beforehand...

2021-12-20 09:28 UTC, to-kn commented
@CarlSchwan since tests are running now, i sqashed the commits again. Let me know if anything is missing

2021-12-20 09:37 UTC, CarlSchwan approved these changes
LGTM

2021-12-21 10:11 UTC, fschrempf approved these changes

2021-12-21 11:34 UTC, merged

2021-12-21 11:34 UTC, CarlSchwan commented
/backport to stable23

2021-12-21 11:34 UTC, CarlSchwan commented
/backport to stable22

2021-12-21 11:34 UTC, CarlSchwan commented
/backport to stable21