[stable23] allow enabling encryption for groupfolders
nextcloud/groupfolders pull request #2103
Opened 2022-09-27 07:58 UTC by PVince81

Manual backport of https://github.com/nextcloud/groupfolders/pull/2068 to stable23

2022-09-27 08:19 UTC, PVince81 commented
I've tested this locally, without encryption and with encryption enabled (need to set the flag with occ config:app:set), and I could see that both encrypted and non-encrypted files could be downloaded.

Newly uploaded files get encrypted.

And the keys are correctly in the system-wide storage.

2022-09-27 08:29 UTC, skjnldsv approved these changes
:elephant:

2022-09-27 09:12 UTC, blizzz requested changes

2022-09-27 09:12 UTC, blizzz commented on lib/Mount/MountProvider.php
> +	private bool $enableEncryption;
typed properties are incompatible with PHP 7.3

2022-09-28 08:36 UTC, PVince81 commented on lib/Mount/MountProvider.php
> +	private bool $enableEncryption;
fixed

2022-09-28 08:40 UTC, blizzz approved these changes

2022-09-28 16:41 UTC, merged