Fix indication of the quota consumed
nextcloud/groupfolders pull request #2244
Opened 2023-01-30 12:13 UTC by Jerome-Herbinet

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

Before : 
![2023-01-30_13-08_1](https://user-images.githubusercontent.com/33763786/215473850-5c37f403-24af-452c-b808-a0a9c98da7bf.png)

After : 
![2023-01-30_13-08](https://user-images.githubusercontent.com/33763786/215473903-01ae3490-7a23-4ee7-bfa2-fc67a415ef4d.png)

2023-02-04 16:28 UTC, susnux commented
This does not work for me, for me it does the opposite: it breaks the quota bars. On NC 26 beta 2 this looks like this:

| Before (current master) | After (this PR) |
|---|---|
| ![quota with bars](https://user-images.githubusercontent.com/1855448/216778464-d298e1fd-2515-4aa8-8d11-8b53fbb5206e.png) | ![quota not visible](https://user-images.githubusercontent.com/1855448/216778473-cccbca1e-472a-4bd5-b8f2-0db30b658cc5.png) |

2023-02-10 09:18 UTC, Jerome-Herbinet commented
> This does not work for me, for me it does the opposite: it breaks the quota bars. On NC 26 beta 2 this looks like this:
> Before (current master) 	After (this PR)
> ![quota with bars](https://user-images.githubusercontent.com/1855448/216778464-d298e1fd-2515-4aa8-8d11-8b53fbb5206e.png) 	![quota not visible](https://user-images.githubusercontent.com/1855448/216778473-cccbca1e-472a-4bd5-b8f2-0db30b658cc5.png)

Hmmmm, strange, I've made some new test, and it's not breaking the UI. But I've noticed a missing property to let appear the background color of used quota (now fixed in a 2nd commit).

2023-03-29 09:09 UTC, koelle25 requested changes
Hi Jerome,
thanks for trying to fix issue #2276!

There are a few changes in this PR that aren't actually needed and some changes would be better suited on other parts.
See my review :)

2023-03-29 09:09 UTC, koelle25 commented on src/settings/EditSelect.scss
> +		border-radius: 0;
Not directly needed to fix issue #2276, but a nice addition anyway. Without it the quotabar "overhangs" the select box a bit. I temporarily made the quotabar background red to better see it in this screenshot:
![2023-03-29_11-04](https://user-images.githubusercontent.com/915514/228484007-8d18fca4-3217-43d8-876b-0c2195901233.png)

With `var(--border-radius-large)`:
![2023-03-29_11-05](https://user-images.githubusercontent.com/915514/228484240-d676a78f-05b8-409a-b5d2-9d5a845c70fe.png)

2023-03-30 08:43 UTC, Jerome-Herbinet commented on src/settings/EditSelect.scss
> +		top: -3px;
Done

2023-03-30 08:43 UTC, Jerome-Herbinet commented on src/settings/EditSelect.scss
> +		height: 36px;
Done

2023-03-30 08:43 UTC, Jerome-Herbinet commented on src/settings/EditSelect.scss
> +		overflow: hidden;
Done

2023-03-30 08:43 UTC, Jerome-Herbinet commented on src/settings/EditSelect.scss
> +		border-radius: 0;
Done

2023-03-30 08:45 UTC, Jerome-Herbinet commented
> Hi Jerome, thanks for trying to fix issue #2276!
> 
> There are a few changes in this PR that aren't actually needed and some changes would be better suited on other parts. See my review :)

Hi @koelle25 ! 
Thank you very much for your review. 
I've followed all your suggestions.
I let you check if it's OK for you.
I remain at your disposal.
Bests regards,
Jérôme

2023-03-30 09:11 UTC, Jerome-Herbinet commented
What it renders now 👍 @koelle25 
![2023-03-30_11-09_1](https://user-images.githubusercontent.com/33763786/228787968-255efcf9-4b98-42b4-b9a4-974d26785d73.png)

2023-03-30 09:12 UTC, Jerome-Herbinet commented
@susnux it should be OK now.

2023-03-30 09:14 UTC, Jerome-Herbinet commented
@icewind1991 @juliushaertl this PR should make GF admin UI "great again" 😅

2023-03-31 07:25 UTC, juliushaertl approved these changes

2023-03-31 07:25 UTC, juliushaertl commented
@Jerome-Herbinet Thanks for that. Could you maybe squash your commits into one?

2023-04-01 11:33 UTC, Jerome-Herbinet commented
Will a "npm run sass" be necessary ?

2023-04-03 06:39 UTC, juliushaertl commented
Not in this repo. Looks good now. Regarding squashing, a descriptive commit message would still be nice as this makes it easier to follow changes that happened later on. Maybe you can just give it a message like "Fix indication of the quota consumed" as the PR title.

2023-04-03 08:06 UTC, Jerome-Herbinet commented
I've tried to add comment, but I'm not sure if it worked, can you confirm ?

2023-04-03 08:18 UTC, juliushaertl commented
It is part of the commit message but the most important one would be the first line as that is what you usually see in git log and the GitHub web ui.

Maybe you can just replace the commit message with a fresh one with `git commit --amend`

2023-04-03 08:32 UTC, Jerome-Herbinet commented
I think it's OK now.

2023-04-03 08:41 UTC, Jerome-Herbinet commented
And thanks also @koelle25 :-)

2023-04-05 15:21 UTC, merged

2023-04-05 15:21 UTC, juliushaertl commented
/backport to stable26

2023-04-05 15:21 UTC, juliushaertl commented
/backport to stable25

2023-04-05 15:21 UTC, juliushaertl commented
/backport to stable24

2023-04-13 21:59 UTC, q-wertz commented
After the update to 13.1.2 there now is an indicator but it still looks wrong…
(NC25.0.5)
![image](https://user-images.githubusercontent.com/20948931/231892133-0a0d84f7-1436-4e99-b545-5600ad7b9719.png)

2023-04-14 08:40 UTC, koelle25 commented
Yeah, it seems NC 25.0.5 brought another few changes which messed this up again :face_exhaling: On 25.0.4 it was working fine :sweat_smile:

2023-04-14 09:12 UTC, q-wertz commented
@koelle25 Thanks for your help :)

Opened an issue. Regarding the color I had the problem that with `--color-background-dark` the text become unreadable so I switched it… :sweat_smile:

2023-04-19 09:24 UTC, Jerome-Herbinet commented
> Yeah, it seems NC 25.0.5 brought another few changes which messed this up again face_exhaling On 25.0.4 it was working fine sweat_smile
> 
> Your proposal looks fine @q-wertz , though I maybe would rather use `background-color: var(--color-background-dark);` like it is used in the extended permissions field.
> 
> Separate issue I just noticed: The extended permissions field is not readable anymore due to a wrong text color it seems: ![2023-04-14_10-41](https://user-images.githubusercontent.com/915514/231992160-bde8e230-1c96-40bb-8d64-2742fbbdf021.png)
> 
> I will open an issue for the second issue. @q-wertz I leave the honor of creating a new issue regarding the quota bar to you slightly_smiling_face

@koelle25 did you finally create an issue concerning ACL appearance ? If yes, I'd like to link my new PR to it (https://github.com/nextcloud/groupfolders/pull/2342)

2023-04-19 10:24 UTC, koelle25 commented
@Jerome-Herbinet Yes, it is here: #2331