fix: fix opening acl create select
nextcloud/groupfolders pull request #2916
Opened 2024-04-09 13:10 UTC by icewind1991

The old way broke when the select was moved to `NcSelect`

2024-04-09 13:11 UTC, icewind1991 commented
/backport to stable28

2024-04-09 14:18 UTC, artonge approved these changes

2024-04-09 16:13 UTC, Pytal requested changes

2024-04-09 16:13 UTC, Pytal commented on src/components/SharingSidebarView.vue
> +					this.$refs.select._vnode.componentInstance.open = true
```suggestion
					this.$refs.select.$el.querySelector('input').focus()
```
This way it will have keyboard focus like before + open the dropdown

2024-04-12 17:06 UTC, Pytal approved these changes

2024-04-12 17:06 UTC, merged